/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject;

import org.junit.jupiter.api.Test;

import com.epam.demo.Utils;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Utils classUnderTest = new Utils();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
